### ISSUE TITLE
Document the `previous_addresses`, `other_addresses` and new (only in new AssemblyLine repo) `mailing_address` attributes

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/doc-assembly-line#37]

**Comment by nonprofittechy** [comment]
Probably only useful as plurals

**Comment by plocket** [comment]
Possible alternative structure - a list of `addresses`, each that have attributes such as `previous`, etc. as an alternative to storing that information in the attribute name. [Also, maybe I'm misunderstanding the described architecture.]

**Comment by nonprofittechy** [comment]
I did consider that for storing mailing address. I'm not sure overhead is
worth it there, for using and collecting that field. Most forms allow one
mailing address. Not clear what you would do if someone added multiple
mailing addresses to the list when it was output time. For that use, we
should probably pick one common use and optimize for it. My hunch is one
mailing address attribute will be easier to work with and cover 90% of use
cases, but I could definitely be convinced otherwise.

Mixing other_addresses with previous_addresses would not make sense. We
decided this several months ago and I think the logic still holds. It would
make it difficult to gather the two kinds of fields on different screens,
which would be normal and easier for the user on most forms.

**Comment by plocket** [comment]
I hear that. Just so I've made sure I've expressed myself clearly, this is the approximate data structure I had intended.
```js
"someone": {
  "addresses": [
    {
      "address": "123 Foo Rd"
      "unit": "2"
      "types": [
        "mailing"
      ]
    }
  ]
}
```

Let me know if this is what you'd understood.

Just to spell it out for future readers of issues who may not be as familiar with da, I assume [one issue] is that to use this in da in the usual way (that is, in-place) would be too cumbersome.

```yml
attachement:
  fields:
    - "user_mailing_address": ${ whatever_annoying_code_is_needed_to_get_just_the_mailing_address }
```

I still often forget the need to evaluate in-place.

[I don't remember exactly what our thinking was we said that this would make it hard to collect other_addresses and previous_addresses on different pages - what it is specifically that would make it hard to do so, so I'd be interested in seeing whatever documentation we produced from that conversation. Alternatively, adding the rationales for this to the documentation that we have so that it's easier to point someone (including me) to it if it comes up again.]
